package com.karanjaa.CarYardManagementSystem.navigation

const val ROUTE_ABOUT = "about"
const val ROUTE_HOME = "home"
const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN= "login"
const val ROUTE_ADD_CARS = "cars"
const val ROUTE_VIEW_CARS="views"
const val ROUTE_UPLOAD_CARS="upload"
const val ROUTE_UPDATE_CARS="update"
const val ROUTE_CAR ="car"
const val ROUTE_LUXURY="Luxury"
const val ROUTE_FAMILY ="family"
const val ROUTE_COMMERCIAL ="commercial"
const val ROUTE_SPORTS ="sports"
const val ROUTE_SPLASH = "splash"
const val ROUTE_FAMILIA="familia"
const val ROUTE_SPORTSS="sport"
const val ROUTE_COMMERCIALL="comm"
const val ROUTE_LURIOUS="luuu"